[workspace]
members = [ "app", "lib", "server" ]

resolver = "2" # Not sure why, but cargo complains if this isn't here

# Optional: workspace-level dependencies or configuration
[workspace.dependencies]

# Shared dependencies can be defined here
# some-common-crate = "0.1.0"
